import { describe, it, expect, beforeEach, vi } from "vitest";

// Mock core for logging
const mockCore = {
  info: vi.fn(),
  debug: vi.fn(),
  warning: vi.fn(),
  error: vi.fn(),
};

global.core = mockCore;

// Import the module
const { buildAIFooter, buildIslandStartMarker, buildIslandEndMarker, findIsland, updateBody } = await import("./update_pr_description_helpers.cjs");

describe("update_pr_description_helpers.cjs", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe("buildAIFooter", () => {
    it("should build AI footer with workflow name and run URL using messages system", () => {
      const footer = buildAIFooter("Test Workflow", "https://github.com/owner/repo/actions/runs/123");
      // Should use the default footer from messages system
      expect(footer).toContain("Test Workflow");
      expect(footer).toContain("https://github.com/owner/repo/actions/runs/123");
      expect(footer).toContain("Generated by"); // Professional message
    });

    it("should handle special characters in workflow name", () => {
      const footer = buildAIFooter("Test & Workflow", "https://github.com/owner/repo/actions/runs/123");
      expect(footer).toContain("Test & Workflow");
    });
  });

  describe("buildIslandStartMarker", () => {
    it("should build island start marker with run ID", () => {
      const marker = buildIslandStartMarker(12345);
      expect(marker).toBe("<!-- gh-aw-island-start:12345 -->");
    });

    it("should handle different run IDs", () => {
      expect(buildIslandStartMarker(1)).toBe("<!-- gh-aw-island-start:1 -->");
      expect(buildIslandStartMarker(999999)).toBe("<!-- gh-aw-island-start:999999 -->");
    });
  });

  describe("buildIslandEndMarker", () => {
    it("should build island end marker with run ID", () => {
      const marker = buildIslandEndMarker(12345);
      expect(marker).toBe("<!-- gh-aw-island-end:12345 -->");
    });

    it("should handle different run IDs", () => {
      expect(buildIslandEndMarker(1)).toBe("<!-- gh-aw-island-end:1 -->");
      expect(buildIslandEndMarker(999999)).toBe("<!-- gh-aw-island-end:999999 -->");
    });
  });

  describe("findIsland", () => {
    it("should find island when both markers are present", () => {
      const body = "Before\n<!-- gh-aw-island-start:123 -->\nIsland content\n<!-- gh-aw-island-end:123 -->\nAfter";
      const result = findIsland(body, 123);
      expect(result.found).toBe(true);
      expect(result.startIndex).toBeGreaterThanOrEqual(0);
      expect(result.endIndex).toBeGreaterThan(result.startIndex);
    });

    it("should not find island when start marker is missing", () => {
      const body = "Before\nIsland content\n<!-- gh-aw-island-end:123 -->\nAfter";
      const result = findIsland(body, 123);
      expect(result.found).toBe(false);
      expect(result.startIndex).toBe(-1);
      expect(result.endIndex).toBe(-1);
    });

    it("should not find island when end marker is missing", () => {
      const body = "Before\n<!-- gh-aw-island-start:123 -->\nIsland content\nAfter";
      const result = findIsland(body, 123);
      expect(result.found).toBe(false);
      expect(result.startIndex).toBe(-1);
      expect(result.endIndex).toBe(-1);
    });

    it("should not find island when run ID does not match", () => {
      const body = "Before\n<!-- gh-aw-island-start:123 -->\nIsland content\n<!-- gh-aw-island-end:123 -->\nAfter";
      const result = findIsland(body, 456);
      expect(result.found).toBe(false);
    });

    it("should handle multiple islands with different run IDs", () => {
      const body = "<!-- gh-aw-island-start:100 -->\nIsland 1\n<!-- gh-aw-island-end:100 -->\n<!-- gh-aw-island-start:200 -->\nIsland 2\n<!-- gh-aw-island-end:200 -->";
      const result1 = findIsland(body, 100);
      const result2 = findIsland(body, 200);
      expect(result1.found).toBe(true);
      expect(result2.found).toBe(true);
      expect(result1.startIndex).toBeLessThan(result2.startIndex);
    });
  });

  describe("updateBody - replace operation", () => {
    it("should replace entire body and add footer", () => {
      const result = updateBody({
        currentBody: "Old content",
        newContent: "New content",
        operation: "replace",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        runId: 123,
      });
      expect(result).toContain("New content");
      expect(result).not.toContain("Old content");
      // Should include footer with workflow information
      expect(result).toContain("Test");
      expect(result).toContain("https://github.com/test/actions/runs/123");
      expect(mockCore.info).toHaveBeenCalledWith(expect.stringContaining("replace"));
    });
  });

  describe("updateBody - append operation", () => {
    it("should append to empty body", () => {
      const result = updateBody({
        currentBody: "",
        newContent: "New content",
        operation: "append",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        runId: 123,
      });
      expect(result).toContain("---");
      expect(result).toContain("New content");
      // Check for footer elements (uses messages system with pirate theme by default)
      expect(result).toContain("Test");
      expect(result).toContain("https://github.com/test/actions/runs/123");
      expect(mockCore.info).toHaveBeenCalledWith(expect.stringContaining("append"));
    });

    it("should append to existing body", () => {
      const result = updateBody({
        currentBody: "Original content",
        newContent: "New content",
        operation: "append",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        runId: 123,
      });
      expect(result).toContain("Original content");
      expect(result).toContain("New content");
      expect(result.indexOf("Original content")).toBeLessThan(result.indexOf("New content"));
    });

    it("should preserve markdown formatting", () => {
      const result = updateBody({
        currentBody: "# Title\n\n**Bold**",
        newContent: "- List item",
        operation: "append",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        runId: 123,
      });
      expect(result).toContain("# Title");
      expect(result).toContain("**Bold**");
      expect(result).toContain("- List item");
    });
  });

  describe("updateBody - prepend operation", () => {
    it("should prepend to empty body", () => {
      const result = updateBody({
        currentBody: "",
        newContent: "New content",
        operation: "prepend",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        runId: 123,
      });
      expect(result).toContain("---");
      expect(result).toContain("New content");
      // Check for footer elements (uses messages system)
      expect(result).toContain("Test");
      expect(result).toContain("https://github.com/test/actions/runs/123");
      expect(mockCore.info).toHaveBeenCalledWith(expect.stringContaining("prepend"));
    });

    it("should prepend to existing body", () => {
      const result = updateBody({
        currentBody: "Original content",
        newContent: "New content",
        operation: "prepend",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        runId: 123,
      });
      expect(result).toContain("Original content");
      expect(result).toContain("New content");
      expect(result.indexOf("New content")).toBeLessThan(result.indexOf("Original content"));
    });
  });

  describe("updateBody - replace-island operation", () => {
    it("should create new island when not found", () => {
      const result = updateBody({
        currentBody: "Original content",
        newContent: "Island content",
        operation: "replace-island",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        runId: 123,
      });
      expect(result).toContain("Original content");
      expect(result).toContain("Island content");
      expect(result).toContain("<!-- gh-aw-island-start:123 -->");
      expect(result).toContain("<!-- gh-aw-island-end:123 -->");
      // Check for footer elements (uses messages system)
      expect(result).toContain("Test");
      expect(result).toContain("https://github.com/test/actions/runs/123");
      expect(mockCore.info).toHaveBeenCalledWith(expect.stringContaining("falling back to append"));
    });

    it("should replace existing island content", () => {
      const currentBody = "Before\n<!-- gh-aw-island-start:123 -->\nOld island\n<!-- gh-aw-island-end:123 -->\nAfter";
      const result = updateBody({
        currentBody,
        newContent: "New island",
        operation: "replace-island",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        runId: 123,
      });
      expect(result).toContain("Before");
      expect(result).toContain("After");
      expect(result).toContain("New island");
      expect(result).not.toContain("Old island");
      expect(result).toContain("<!-- gh-aw-island-start:123 -->");
      expect(result).toContain("<!-- gh-aw-island-end:123 -->");
      expect(mockCore.info).toHaveBeenCalledWith(expect.stringContaining("updating existing island"));
    });

    it("should preserve content outside island when replacing", () => {
      const currentBody = "# Title\n\nSome intro\n\n<!-- gh-aw-island-start:123 -->\nOld\n<!-- gh-aw-island-end:123 -->\n\n## Footer\n\nMore content";
      const result = updateBody({
        currentBody,
        newContent: "Updated content",
        operation: "replace-island",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        runId: 123,
      });
      expect(result).toContain("# Title");
      expect(result).toContain("Some intro");
      expect(result).toContain("## Footer");
      expect(result).toContain("More content");
      expect(result).toContain("Updated content");
      expect(result).not.toContain("Old");
    });

    it("should not replace island with different run ID", () => {
      const currentBody = "Before\n<!-- gh-aw-island-start:456 -->\nOther island\n<!-- gh-aw-island-end:456 -->\nAfter";
      const result = updateBody({
        currentBody,
        newContent: "New island",
        operation: "replace-island",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        runId: 123,
      });
      // Should append because island 123 doesn't exist
      expect(result).toContain("Other island");
      expect(result).toContain("New island");
      expect(result).toContain("<!-- gh-aw-island-start:456 -->");
      expect(result).toContain("<!-- gh-aw-island-start:123 -->");
      expect(mockCore.info).toHaveBeenCalledWith(expect.stringContaining("falling back to append"));
    });

    it("should handle multiple islands with same run ID (replace first)", () => {
      const currentBody = "<!-- gh-aw-island-start:123 -->\nFirst\n<!-- gh-aw-island-end:123 -->\n<!-- gh-aw-island-start:123 -->\nSecond\n<!-- gh-aw-island-end:123 -->";
      const result = updateBody({
        currentBody,
        newContent: "Replaced",
        operation: "replace-island",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        runId: 123,
      });
      expect(result).toContain("Replaced");
      // First island should be replaced
      expect(result.indexOf("Replaced")).toBeLessThan(result.indexOf("Second"));
    });

    it("should handle empty island content", () => {
      const currentBody = "Before\n<!-- gh-aw-island-start:123 -->\n\n<!-- gh-aw-island-end:123 -->\nAfter";
      const result = updateBody({
        currentBody,
        newContent: "New content",
        operation: "replace-island",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        runId: 123,
      });
      expect(result).toContain("New content");
      expect(result).toContain("Before");
      expect(result).toContain("After");
    });

    it("should handle special characters in island content", () => {
      const currentBody = "<!-- gh-aw-island-start:123 -->\nOld\n<!-- gh-aw-island-end:123 -->";
      const result = updateBody({
        currentBody,
        newContent: "Content with **markdown**, `code`, [links](http://example.com)",
        operation: "replace-island",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        runId: 123,
      });
      expect(result).toContain("**markdown**");
      expect(result).toContain("`code`");
      expect(result).toContain("[links](http://example.com)");
    });

    it("should handle newlines and whitespace correctly", () => {
      const currentBody = "<!-- gh-aw-island-start:123 -->\n  \n\nOld\n\n  \n<!-- gh-aw-island-end:123 -->";
      const result = updateBody({
        currentBody,
        newContent: "New\n\nMultiline\n\nContent",
        operation: "replace-island",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        runId: 123,
      });
      expect(result).toContain("New\n\nMultiline\n\nContent");
    });
  });

  describe("updateBody - edge cases", () => {
    it("should handle empty new content", () => {
      const result = updateBody({
        currentBody: "Original",
        newContent: "",
        operation: "append",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        runId: 123,
      });
      expect(result).toContain("Original");
      // Check for footer elements
      expect(result).toContain("Test");
    });

    it("should handle empty current body", () => {
      const result = updateBody({
        currentBody: "",
        newContent: "New",
        operation: "append",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        runId: 123,
      });
      expect(result).toContain("New");
    });

    it("should handle unicode characters", () => {
      const result = updateBody({
        currentBody: "Original 你好",
        newContent: "New 世界 🚀",
        operation: "append",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        runId: 123,
      });
      expect(result).toContain("你好");
      expect(result).toContain("世界 🚀");
    });

    it("should handle very long content", () => {
      const longContent = "A".repeat(10000);
      const result = updateBody({
        currentBody: "Original",
        newContent: longContent,
        operation: "append",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        runId: 123,
      });
      expect(result).toContain(longContent);
      expect(result.length).toBeGreaterThan(10000);
    });

    it("should handle default to append for unknown operation", () => {
      const result = updateBody({
        currentBody: "Original",
        newContent: "New",
        operation: "unknown",
        workflowName: "Test",
        runUrl: "https://github.com/test/actions/runs/123",
        runId: 123,
      });
      expect(result).toContain("Original");
      expect(result).toContain("New");
      expect(result).toContain("---");
      expect(mockCore.info).toHaveBeenCalledWith(expect.stringContaining("append"));
    });
  });
});
