package workflow

import (
	_ "embed"
	"fmt"
	"strings"

	"github.com/github/gh-aw/pkg/constants"
	"github.com/github/gh-aw/pkg/logger"
)

var headerLog = logger.New("workflow:header")

//go:embed assets/logo.txt
var headerAsciiLogo string

// GenerateWorkflowHeader generates the standard header comment for generated workflow files.
// It includes the ASCII art logo and instructions on how to regenerate the file.
//
// Parameters:
//   - sourceFile: The source file path (e.g., ".md" file) that generated this workflow, or empty if not applicable
//   - generatedBy: Description of what generated this file (e.g., "gh-aw", "pkg/workflow/maintenance_workflow.go")
//   - customInstructions: Optional additional instructions to display after the standard regeneration instructions
func GenerateWorkflowHeader(sourceFile string, generatedBy string, customInstructions string) string {
	headerLog.Printf("Generating workflow header: sourceFile=%s, generatedBy=%s, hasCustomInstructions=%v",
		sourceFile, generatedBy, customInstructions != "")

	var header strings.Builder

	// Add ASCII logo
	header.WriteString("#\n")
	// TrimRight removes only trailing newlines, preserving per-line leading spaces
	logoLines := strings.Split(strings.TrimRight(headerAsciiLogo, "\n"), "\n")
	headerLog.Printf("Adding ASCII logo with %d lines", len(logoLines))
	for _, line := range logoLines {
		fmt.Fprintf(&header, "# %s\n", line)
	}
	header.WriteString("#\n")

	// Add auto-generated disclaimer
	// Include version for released builds only (not "dev")
	if generatedBy != "" {
		if IsReleasedVersion(GetVersion()) {
			fmt.Fprintf(&header, "# This file was automatically generated by %s (%s). DO NOT EDIT.\n", generatedBy, GetVersion())
		} else {
			fmt.Fprintf(&header, "# This file was automatically generated by %s. DO NOT EDIT.\n", generatedBy)
		}
	} else {
		header.WriteString("# This file was automatically generated. DO NOT EDIT.\n")
	}
	header.WriteString("#\n")

	// Add regeneration instructions
	if sourceFile != "" {
		fmt.Fprintf(&header, "# To update this file, edit %s and run:\n", sourceFile)
	} else {
		header.WriteString("# To regenerate this workflow, run:\n")
	}
	header.WriteString("#   " + string(constants.CLIExtensionPrefix) + " compile\n")
	header.WriteString("# For more information: https://github.com/github/gh-aw/blob/main/.github/aw/github-agentic-workflows.md\n")

	// Add custom instructions if provided
	if customInstructions != "" {
		header.WriteString("#\n")
		// Split custom instructions into lines and prefix each with "# "
		instructionLines := strings.Split(strings.TrimSpace(customInstructions), "\n")
		headerLog.Printf("Adding %d lines of custom instructions", len(instructionLines))
		for _, line := range instructionLines {
			fmt.Fprintf(&header, "# %s\n", strings.TrimSpace(line))
		}
	}

	header.WriteString("#\n")

	headerLog.Printf("Generated header with %d bytes", header.Len())
	return header.String()
}
